on:
  push:
    branches: [develop]
  pull_request:
    branches: develop

name: spelling-check

jobs:
  spelling-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - uses: actions/checkout@v6
      
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install spellchecker
        run: install.packages("spelling")
        shell: Rscript {0}

      - name: Spellcheck root directory (include vignettes)
        id: spellcheck # Assign ID to this step for output
        run: |
          result <- spelling::spell_check_package()
          result
          if (length(result[[1]]) != 0) {
            stop("Spelling errors found (fix or add to WORDLIST)")
          }
        shell: Rscript {0}
